name: Security Analysis

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  osv-scanner:
    name: OSV Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run OSV Scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          path: .
          
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: osv-results.sarif
          category: "OSV Scanner Results"

  semgrep:
    name: Semgrep Analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Semgrep Analysis
        run: |
          semgrep --config=p/java . --sarif
          
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
          category: "Semgrep Results"
